### ISSUE TITLE
BUG: The application does not run

### ISSUE THREAD

**Issue by arturotrenard** [nchia-net/ext9-blockchain#1]
The version from the repository does not work: 
git clone https://gitee.com/ext9/ext9-blockchain.git -b net9.dev  --recurse-submodules

Daemon not started yet
Starting daemon
chia_harvester: started
chia_farmer: started
chia_full_node: started
Traceback (most recent call last):
  File "/home/ext9-blockchain/venv/bin/chia_full_node", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_full_node')())
  File "/home/ext9-blockchain/venv/bin/chia_full_node", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ext9-blockchain/chia/server/start_full_node.py", line 8, in <module>
    from chia.full_node.full_node import FullNode
  File "/home/ext9-blockchain/chia/full_node/full_node.py", line 16, in <module>
    from chia.consensus.blockchain import Blockchain, ReceiveBlockResult
  File "/home/ext9-blockchain/chia/consensus/blockchain.py", line 2, in <module>
    from asyncio.windows_events import NULL
  File "/usr/lib/python3.8/asyncio/windows_events.py", line 3, in <module>
    import _overlapped
ModuleNotFoundError: No module named '_overlapped'

My operating system is Ubuntu 20.04 LTS

**Comment by nchia-net** [comment]
did you followed steps below:
```bash
git clone https://gitee.com/ext9/ext9-blockchain.git -b net9.dev  --recurse-submodules
cd ext9-blockchain
sh install.sh
. ./activate
chia start farmer
```

**Comment by nchia-net** [comment]
without use 
```.  ./activate```
 command ,pip installed packages in venv folders won't works. So you got  errors above
